[General]
# Ninja + local proxy providers
DOWNLOAD_FILE = url=https://raw.githubusercontent.com/K1LLSCRIPT/rulesets/refs/heads/main/template/clash-overwrite/ninja_v2.yaml, path=/etc/openclash/config/ninja_v2.yaml, force=true
CONFIG_FILE = /etc/openclash/config/ninja_v2.yaml
RESTART = true

[Overwrite]
ruby_cover "$CONFIG_FILE" "['proxy-providers']" "/etc/openclash/proxy_provider/proxy_prov.yaml" "proxy-providers"
